### ISSUE TITLE
"/pcraft help" does not help

### ISSUE THREAD

**Issue by Flavescent** [Jaksuhn/SomethingNeedDoingLegacy#128]
The readme says, "Type /pcraft help for some help."

However, this command only opens an empty "debug" window that cannot be closed:

![image](https://github.com/Jaksuhn/SomethingNeedDoing/assets/12690771/97714c13-c2ed-4899-949b-8fc9584aeeb2)

As an aside, there appears to be no documented command and no button to open the settings screen that apparently exists, as per a Discord screenshot:

![image](https://github.com/Jaksuhn/SomethingNeedDoing/assets/12690771/0af966bd-da52-499c-a822-bd99a63416c3)

**Comment by Jaksuhn** [comment]
the command is `/pcraft help`, and  there's also the `?` button inside the main menu to access the help menu. As for why it's showing the debug window for you, I have no idea. It's possible the actual window is being draw off screen in which case you'd need to delete its record from your dalamudUI file to refresh its state

**Comment by Flavescent** [comment]
Thanks for the quick reply, it was indeed the window offscreen problem.
