### ISSUE TITLE
The command /pinteract does not exist.

### ISSUE THREAD

**Issue by StarkITA** [Jaksuhn/SomethingNeedDoingLegacy#154]
I reported it in a script, but I figured I may report it here as well

As reported in https://github.com/plottingCreeper/FFXIV-scripts-and-macros/issues/1, the command /pinteract seems to not exist anymore, but I do not know it if is SND or something else :)

**Comment by Jaksuhn** [comment]
That was a pandora's box command, and since pandora isn't updated, it's not there. There is, however, the /interact command in snd

**Comment by StarkITA** [comment]
Thanks!
