### ISSUE TITLE
Adding HQ Mats to Recipe click is missing?

### ISSUE THREAD

**Issue by SMallick4163** [Jaksuhn/SomethingNeedDoingLegacy#158]
Hi! I'm not sure if there is a better place to ask this or not. If so, can you point me in the right direction? I had used the original plugin a long time ago and one of the click commands I would use was the following:

/click synthesis_materialX_hq

Where X was the row of the intermediate material you wanted to make HQ before crafting a given recipe. Currently this click gives the following error:

[SND] Failure while running /click synthesis_material1_hq (step 3): Unexpected click error

I checked the help menu click section as well as the other sections and I checked the wiki, but I don't see any replacement click or substitute for this function.

Thanks!

**Comment by StarkITA** [comment]
Been having the same issue with /click

> [12:51][SND] Failure while running /click select_retainer1 (step 20): Unexpected click error

I think that it's a /click issue?

Though it's not been reported yet, and I am sure that people are *really* using this plugin, maybe it's already known?

**Comment by StarkITA** [comment]
In https://github.com/Jaksuhn/SomethingNeedDoing/issues/155#issuecomment-2209591879 it is mentioned that commands have been updated!

**Comment by hypnotizdb** [comment]
Using the old name you'd do `/click synthesis_material<x>_hq` i.e. `/click synthesis_material1_hq` but with the new name `/click RecipeNote_Material1_hq` doesn't work, doesn't put an error in chat, `/click RecipeNote_Material` puts an Unexpected click error in chat, I've tried a few different permutations but no luck, anyone figure it out?

Here's what the function looks like in [RecipeNote.cs](https://github.com/NightmareXIV/ECommons/blob/master/ECommons/UIHelpers/AddonMasterImplementations/RecipeNote.cs)
```cs
public void Material(uint index, bool hq)
{
    if (hq) index += 0x10_000;
    Callback.Fire(Base, false, 6, index, 0);
}
```

**Comment by hypnotizdb** [comment]
For anyone else having this issue, I gave up on the click function for now, using [callback](https://github.com/Jaksuhn/SomethingNeedDoing/wiki/Callback-and-How-to-use-them) instead
Check the crafting log is active `IsAddonReady("RecipeNote")`
Use callbacks the same way you would clicks `yield("/callback RecipeNote true 6 " .. 65535 + i)` here `i` is any number from 1 to 6 for the 6 different materials top to bottom
To check how many are selected you can do `GetNodeText("RecipeNote", 24 - i, 6, 2)`, this will return an empty string for slots that aren't applicable

**Comment by Jaksuhn** [comment]
the format will be `/click RecipeNote Material 0 true` in the next update, I'll close the issue when it's released, but I'm just saying this now

**Comment by Jaksuhn** [comment]
click update is live, apologies for the delay
