### ISSUE TITLE
RunMacro and Click commands cause unexpected errors

### ISSUE THREAD

**Issue by Kyleo91** [Jaksuhn/SomethingNeedDoingLegacy#184]
![image](https://github.com/user-attachments/assets/fe5e6f59-acf2-493e-aabc-93ac591a9375)

Noticed this for a week or so now that the /runmacro command is causing the above error - tested my other macros and noted that /click also provides the same error message. This is on version 1.28

**Comment by Jaksuhn** [comment]
tell me if 29 fixes it

**Comment by Kyleo91** [comment]
Updated to 29, restarted game - same error message

**Comment by Jaksuhn** [comment]
can you give me some verbatim commands that are causing this

**Comment by Kyleo91** [comment]
When attempting to use a macro for crafting /click "Synthesize" <wait.2> causes the error, for runmacro:
![image](https://github.com/user-attachments/assets/9cb6a502-502c-4ede-bb86-e845d18e5a98)
of which the macro in question is: 
![image](https://github.com/user-attachments/assets/0f99a5f5-4e1b-43e8-85c4-0c34619fac54)
but it doesn't even reach that point to start the macro it fails before then

**Comment by Jaksuhn** [comment]
Logically I don't really understand how it could be producing that error given the code but eh. I've just removed wait support from clicks so your thing will work now. Though that second picture you sent has the old-new and not new-new click names

**Comment by Kyleo91** [comment]
That explains a lot...didn't realise there had been another change to the click names and that's what was causing it, my bad!
