### ISSUE TITLE
GetItemCount()

### ISSUE THREAD

**Issue by Ecselsior** [Jaksuhn/SomethingNeedDoingLegacy#193]
I have an issue with the GetItemCount() command returning an incorrect value.

When I ran the command below, I got a returned value of 33 when I had 11 Baked Eggplants hq in my inventory.
```
yield("/e " .. GetItemCount(1039872, true))
```
When I ate one BakedEggplant hq and ran it again (i.e. I now only have 10 BakedEggplants), it returned a value of 30.
I am not sure why it think I have 3 times as many Baked Eggplans as I currently do. I do not have any NQ baked eggplants in my inventory.

![image](https://github.com/user-attachments/assets/07d5e5a3-9505-404b-8415-10688bd3bc5e)
![image](https://github.com/user-attachments/assets/89cce61c-9c6b-449b-8462-e13fdb6cbaf1)
![image](https://github.com/user-attachments/assets/e56d08a1-391e-4c2c-83ce-da2d2976c457)
8 was the correct value of "Squadron Gear Maintenance Manual" I had in my inventory.

---
I repeated this test with Vegetable Soup hq:
```
yield("/e Number of Vegetable Soups: " .. GetItemCount(1044096, true))
```
![image](https://github.com/user-attachments/assets/79eca667-fe6c-4566-b665-3807e8bc5e8d)
While I had 13 Vegtable Soup hq in my inv:
![image](https://github.com/user-attachments/assets/79df4420-d8f8-47ce-b02e-dab85bca4b9b)
While I had 12 Vegetable Soup hq in my inv:
![image](https://github.com/user-attachments/assets/80bfc48a-12e7-4829-8e5b-d8b94132a453)

I lowered the quality of one baked eggplant and it seems that baked eggplant nq has a different itemid than hq:
![image](https://github.com/user-attachments/assets/54fff185-53b0-445d-9261-daafd63725d9)
When I run the same command with this itemID, the lua command functions correctly (I had 9 hq and 1 nq).
![image](https://github.com/user-attachments/assets/0e011d4b-99ae-4e6e-afa5-c7bf2c2c4037)

---
As in the script I am making uses ```"/item Baked Eggplant <hq>"``` to attempt to consume food, it is important that I can check that if have a valid amount in my inventory. There is a workaround:
```
item_hq_count = GetItemCount(39872, true) - GetItemCount(39872, false)
```
Also, is it possible if you could make GetItemCount() to work with the item name, or allow me to call SearchItemId() as in ItemCommand.cs in my script? Currently I'm having to manually find the itemId using S*mpleTweaks debug.

**Comment by McVaxius** [comment]
is s-i-m-p a banned word on github is that why the censoring? hehe

also thats neat thanks for finding that. i may need to use that work around

**Comment by Jaksuhn** [comment]
Your problem was passing in the HQ item id. The way item IDs work in this game is that HQ is just 1,000,000 + id. You cannot pass the 1m+ value to GetItemCount. If you want to count hq items, pass the regular item id and true
