### ISSUE TITLE
IsNodeVisible()

### ISSUE THREAD

**Issue by hypnotizdb** [Jaksuhn/SomethingNeedDoingLegacy#195]
`IsNodeVisible()` seems to return `false` for any node I try, my specific use case is checking which material slots are being used on a crafting recipe `IsNodeVisible("RecipeNote",23,15)` or `IsNodeVisible("RecipeNote",23)` using the same values as in `GetNodeText("RecipeNote",23,15)` that I used to get how much of a material the recipe costs.

I've tried `IsNodeVisible()` on many different addons and no matter what I point it to I can't get it to return `true`, like with `GetNodeText()` an invalid node simply returns the last node id instead.

Anyone know another way to do this in the meantime? Maybe some way to retrieve the Flags on a node?

**Comment by Jaksuhn** [comment]
your node id chain is wrong, start from the root

**Comment by hypnotizdb** [comment]
I see my issue, I was mistaking node numbers for node ids, GetNodeText using numbers and IsNodeVisible using ids
