### ISSUE TITLE
DeliverooIsTurnInRunning() does not return bool

### ISSUE THREAD

**Issue by pot0to** [Jaksuhn/SomethingNeedDoingLegacy#206]
`DeliverooIsTurnInRunning()` returns `function: 00007FF87B205CBC`
`DeliverooIsTurnInRunning()()` causes error `[SND] Failure while running script: function`

![image](https://github.com/user-attachments/assets/ef07fe62-1f1c-49e8-b771-4456e7280cee)

![image](https://github.com/user-attachments/assets/859b7fe5-c563-46c1-aaa5-3aacee94125c)

**Comment by Jaksuhn** [comment]
yes it does https://github.com/Jaksuhn/SomethingNeedDoing/blob/f93f2134a9225e4cb11728de88bcdc53f1aa646e/SomethingNeedDoing/Misc/Commands/IpcCommands.cs#L67
