### ISSUE TITLE
Is there a way to get history version of this plugin?

### ISSUE THREAD

**Issue by StackExplode** [Jaksuhn/SomethingNeedDoingLegacy#255]
Hi, I love your plugin. Thank you for your contribution.
I come from CN server with APILevel 10 which is behind others. Is there a way to get an older version?

**Comment by Jaksuhn** [comment]
[SomethingNeedDoing-1.53.zip](https://github.com/user-attachments/files/18186633/SomethingNeedDoing-1.53.zip)

I keep an old version pinned in the puni.sh discord btw
