### ISSUE TITLE
OpenRegularDuty(264) Leads to Brayflox (should lead to Emanation)

### ISSUE THREAD

**Issue by LuncBB** [Jaksuhn/SomethingNeedDoingLegacy#43]
OpenRegularDuty(264), among some other IDs, do not pull up the suggested duty. 264 says it should be emanation but it pulls up brayflox instead, some IDs do work though like 115 goes to alexander burden. It was suggested that some IDs are not fully static and so unlocking everything might fix it. If I get to that point to test I'll let you know lol. Emenation is unlocked content for context.

**Comment by Jaksuhn** [comment]
fixed in 1.6.6.2
