### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by McVaxius** [Jaksuhn/SomethingNeedDoingLegacy#84]
hi sir

i would love for the following to exist for some scripts i have in flight atm

1. checking remaining duration on my chocobro
2. getting char condition of specific party member or targeted player (such as mounted, quueing, in combat, etc)

**Comment by Jaksuhn** [comment]
I can't do queueing. Other players don't have a `Condition` to check. Some of those are doable like mounting and in combat (and will be in the next release) but anything else I'd need specific requests for.

**Comment by McVaxius** [comment]
<3
